# Generated by Django 5.0.6 on 2024-06-19 01:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_courier_fcm_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='stripe_card_last4',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='stripe_customer_id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='stripe_payment_method_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='stripe_payment_intent_id',
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='courier',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
